# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

jobs:
  build:
    docker:
      - image: cirrusci/flutter:latest
      
    steps:
      - checkout

      - run:
          name: Flutter doctor
          command: flutter doctor
      
      - run:
          name: Running tests
          command: flutter test
      
      - run:
          name: Building app
          command: flutter build

workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
        filters:
          branches:
            only: master
